### ISSUE TITLE
BCE损失非常大正常吗？

### ISSUE THREAD

**Issue by aflyingnoob** [JosephChenHub/GCPANet#10]
使用BCE损失时候，输出和label在0/1和1/0时候会导致损失非常大，训练时候出现了4位数的损失。。。

**Comment by JosephChenHub** [comment]
> 使用BCE损失时候，输出和label在0/1和1/0时候会导致损失非常大，训练时候出现了4位数的损失。。

what's the initial learning rate? you might need to check the input and target.

**Comment by aflyingnoob** [comment]
1e-4 with adam，and i have checked the inputs which range from 0-1, labels are also either 0 or1。

**Comment by aflyingnoob** [comment]
targets also have applied sigmoid。 The results are not bad and I get the rough salient maps，but the loss is very big. I'll check it carefully, thanks.

**Comment by JosephChenHub** [comment]
> 1e-4 with adam，and i have checked the inputs which range from 0-1, labels are also either 0 or1。

how about use SGD ?  I  rarely use the adam.

**Comment by aflyingnoob** [comment]
I think this may be caused by the formula of the BCE loss: the label is 256x256 pixel which consists of 1 and 0，the outputs of the network are also 256*256，but all of the 65536 pixels can not predict well at the same time，even only a label is 1 and the output is 0，then log (0) will increase the loss dramatically. I‘m so confused about this problem，have you ever experienced this? Thanks

**Comment by JosephChenHub** [comment]
> I think this may be caused by the formula of the BCE loss: the label is 256x256 pixel which consists of 1 and 0，the outputs of the network are also 256*256，but all of the 65536 pixels can not predict well at the same time，even only a label is 1 and the output is 0，then log (0) will increase the loss dramatically. I‘m so confused about this problem，have you ever experienced this? Thanks

I would like to offer some tips:
1. set the parameter `reduction=None`, then you can apply different weights for positive and negative labels, or just replace the factor `1/65536 ` with a larger constant; 
2. combining the CE loss with the  `Dice loss` or `focal loss`.

**Comment by YinMange-Mandy** [comment]
> 使用BCE损失时候，输出和label在0/1和1/0时候会导致损失非常大，训练时候出现了4位数的损失。
您好，请问您复现实验的结果与原文一致吗？我复现出来得到mae有0.4xxx。复现了很多遍都是这样，但是不知道怎么解决，

**Comment by aflyingnoob** [comment]
> 

0.4太夸张了, 是你的代码问题. 0.4不就是没训练吗. 另外不建议卷这个方向了. 指标做不动了. 半监督/无监督可能会好点.

**Comment by YinMange-Mandy** [comment]
我的代码就是从这个原作者的链接里po下来的，然后一直复现都是这样的结果。主要是我已经拿这个方向开题了，只能硬着头皮继续。这也是我比较疑惑的地方，不知道是哪里出问题了。您复现的结果和原文差不多吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JosephChenHub/GCPANet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月27日(星期一) 下午5:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JosephChenHub/GCPANet] BCE损失非常大正常吗？ (#10)





   
0.4太夸张了, 是你的代码问题. 0.4不就是没训练吗. 另外不建议卷这个方向了. 指标做不动了. 半监督/无监督可能会好点.

**Comment by aflyingnoob** [comment]
我忘记了, 你debug下吧, 0.4就是网络直接没训练了. 即使用最原始的u-net做也能得到不错的效果, 你再加点东西, 毕业还是很好解决的.

**Comment by YinMange-Mandy** [comment]
好的，谢谢您的回复。您是已经毕业了吗？&nbsp; 您毕业方向也是这个相关吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JosephChenHub/GCPANet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月27日(星期一) 下午5:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JosephChenHub/GCPANet] BCE损失非常大正常吗？ (#10)





 
我忘记了, 你debug下吧, 0.4就是网络直接没训练了. 即使用最原始的u-net做也能得到不错的效果, 你再加点东西, 毕业还是很好解决的.
