### ISSUE TITLE
Trainning

### ISSUE THREAD

**Issue by 18718277909** [JosephChenHub/GCPANet#11]
Hello,  thanks for your contribution.
I want to ask why I got the model name after training is model-, and there is no model with model-.pt.？
What's the role of tag and how do I set it？
Can you answer for me, please? Thank you

**Comment by JosephChenHub** [comment]
> Hello, thanks for your contribution.
> I want to ask why I got the model name after training is model-, and there is no model with model-.pt.？
> What's the role of tag and how do I set it？
> Can you answer for me, please? Thank you

see https://github.com/JosephChenHub/GCPANet/blob/master/train.py#L114 ,  the model is saved as `model-[epoch]` and I just rename it as `model-xxx.pt`.

**Comment by 18718277909** [comment]
> > Hello, thanks for your contribution.
> > I want to ask why I got the model name after training is model-, and there is no model with model-.pt.？
> > What's the role of tag and how do I set it？
> > Can you answer for me, please? Thank you
> 
> see https://github.com/JosephChenHub/GCPANet/blob/master/train.py#L114 , the model is saved as `model-[epoch]` and I just rename it as `model-xxx.pt`.

but why I use the command to test it, I just get many empty file folder？
