### ISSUE TITLE
结果图全灰色

### ISSUE THREAD

**Issue by LitterWindwind** [JosephChenHub/GCPANet#13]
您好，我自己训练的模型测试了一下，结果成了全灰色 MAE当然也特别大 0.5左右。 训练步骤有什么需要注意的吗

**Comment by JosephChenHub** [comment]
> 您好，我自己训练的模型测试了一下，结果成了全灰色 MAE当然也特别大 0.5左右。 训练步骤有什么需要注意的吗

have you followed the steps in the README.md ?

**Comment by YinMange-Mandy** [comment]
> 您好，我自己训练的模型测试了一下，结果成了全灰色 MAE当然也特别大 0.5左右。 训练步骤有什么需要注意的吗

您好，我复现也是您这样的情况，请问您解决了吗？如果解决的话能否 把您解决的方法教我一下？

**Comment by YinMange-Mandy** [comment]
> > 您好，我自己训练的模型测试了一下，结果成了全灰色 MAE当然也特别大 0.5左右。 训练步骤有什么需要注意的吗
> 
> have you followed the steps in the README.md ?

I have followed your README.md to have the experiment for five times, the results are also like litterwindwind said.
