### ISSUE TITLE
IndexError: list index out of range请问这是什么情况？

### ISSUE THREAD

**Issue by StormArcher** [JosephChenHub/GCPANet#3]
python test.py之后遇到报错如下

Testing on SOD
Traceback (most recent call last):
  File "test.py", line 105, in <module>
    t = Test(dataset, e, GCPANet)
  File "test.py", line 47, in __init__
    self.cfg = Dataset.Config(datapath=datapath, snapshot=sys.argv[1], mode='test')
IndexError: list index out of range

**Comment by JosephChenHub** [comment]
please run this command ``python3 test.py model-xxx.pt '', since **snapshot** must be provided in the inference stage.
