### ISSUE TITLE
想引用你的文章，有没有bibi格式

### ISSUE THREAD

**Issue by StormArcher** [JosephChenHub/GCPANet#4]
想引用你的文章，有没有bibi格式

**Comment by lartpang** [comment]
我觉得作者可以暂时将论文传到arxiv上...

**Comment by hali1122** [comment]
> 想引用你的文章，有没有bibi格式

请问您也是做图像显著性检测的吗？不知道你们在DUTS-TR数据集上的训练MAE能够达到多少？我在做的时候，在DUTS-TR上的效果挺好的 ，但在其他测试用数据集上的效果就不那么理想了。

**Comment by StormArcher** [comment]
为什么在训练集上测试

**Comment by ChinChyi** [comment]
> 为什么在训练集上测试

DUTS分两部分的，DUTS-TEST和DUTS-TRAIN，所以训练集和测试集应该是不一样的
