### ISSUE TITLE
Increasing model learning capacity

### ISSUE THREAD

**Issue by SysDevHayes** [JosephChenHub/GCPANet#8]
Dear JosephChen,

Firstly, I want to tank you so much for this amazing work. I have a question which is I have a relatively big dataset (150000 images). When the training start, it when down quite fast, then stall after around 40 Epoches. I guess this was due to the limit of the learning capacity of this model. Is that possible to increase the learning capacity? If so, please give me a guidance how to do that. 

Thank you so much!

**Comment by JosephChenHub** [comment]
> Dear JosephChen,
> 
> Firstly, I want to tank you so much for this amazing work. I have a question which is I have a relatively big dataset (150000 images). When the training start, it when down quite fast, then stall after around 40 Epoches. I guess this was due to the limit of the learning capacity of this model. Is that possible to increase the learning capacity? If so, please give me a guidance how to do that.
> 
> Thank you so much!

Hi, I would like to recommend you on several trials : 

- Does the model really over-fitting your custom dataset? 
- Have you ever evaluated the trained model on your dataset?  
- How about replacing the backbone with larger models such as ResNet101?
