### ISSUE TITLE
How to train to achieve the results of the paper（model_100045448.pt）

### ISSUE THREAD

**Issue by lesonly** [JosephChenHub/GCPANet#9]
Thank you very much for the concise code provided by the author, which makes me gain a lot！But I have some confusion。According to this code, set batchsize to 32. After 30 epochs of training, the result of SOD is MAE = 0.49, F-Score = 0.35, which is quite different from the results of "model_100045448.pt". Could you tell me where the problem is ？Thanks a million！

**Comment by YinMange-Mandy** [comment]
> Thank you very much for the concise code provided by the author, which makes me gain a lot！But I have some confusion。According to this code, set batchsize to 32. After 30 epochs of training, the result of SOD is MAE = 0.49, F-Score = 0.35, which is quite different from the results of "model_100045448.pt". Could you tell me where the problem is ？Thanks a million！

Hi，I want to know if you solve the problem. My results are as the same as yours. If you sloved this issue, could you tell me  the way ?
